### ISSUE TITLE
Budget report

### ISSUE THREAD

**Issue by mportesdev** [berk76/eu2020#16]
Ahoj,
zkoušel jsem, jestli by se dalo využít [string.Template](https://docs.python.org/3/library/string.html#string.Template) pro generování tabulky s rozpočtem. Funguje je to, ale nevím jestli je to nějaký extra přínos oproti původnímu kódu.

Raději to zatím nechávám v separátní větvi [budget_report_template](https://github.com/berk76/eu2020/tree/budget_report_template), koukni na to.

Michal

**Comment by berk76** [comment]
Ahoj Michale,

koukám na to a musím říci že se mi to líbí. Klidně to mergni.

Jarda
